In [1]:
import numpy as np


Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

INT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [123]:
def ATV(x,N):
    raw_array = np.array([],dtype=int)
    for i in range(N):
        t= np.power(x, i)
        raw_array=np.append(t,raw_array)
    arr=raw_array.reshape(N,len(x)).T
    return arr
        
    
    

Test with an example

In [124]:
a=np.array([1,2,3,4])

In [125]:
len(a)

4

In [126]:
arr= ATV(a,3)

In [127]:
arr

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1]])

Question = Write a function to find moving average in an array over a window:

In [149]:
def moving_avg_arr(arr, window):
    l =[]
    for i in range(len(arr) - window + 1):
        value = 0
        for k in range(window):
            value = value + arr[k+i]
        average_value = value/window
        l.append(average_value) 
    return l
    

testing via an example 

In [150]:
a= np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])

In [151]:
a

array([  3,   5,   7,   2,   8,  10,  11,  65,  72,  81,  99, 100, 150])

In [152]:
output_list = moving_avg_arr(a,3)

In [153]:
output_list

[5.0,
 4.666666666666667,
 5.666666666666667,
 6.666666666666667,
 9.666666666666666,
 28.666666666666668,
 49.333333333333336,
 72.66666666666667,
 84.0,
 93.33333333333333,
 116.33333333333333]

In [154]:
moving_averages = np.array(output_list)

In [155]:
moving_averages

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])